<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="chassis_size_x" value="0.4" />
<xacro:property name="chassis_size_y" value="0.4" />
<xacro:property name="chassis_size_z" value="0.4" />
<xacro:property name="wheel_radius" value="0.2" />
<xacro:property name="wheel_length" value="0.05" />
<xacro:property name="ground_gap_offset" value="0.1" />
<xacro:property name="small_wheel_radius" value="0.05" />
<xacro:property name="small_wheel_length" value="0.025" />

<xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo"/>



<link name="robot_footprint"></link>

<joint name="robot_footprint" type="fixed">
<orgin xyz="0 0 0" rpy="0 0 0"/>
<parent link="robot_footprint"/>
<child link="chassis"/>
</joint>

<link name='chassis'>
    <pose xyz="0 0 ${chassis_size_z}" rpy="0 0 0" />
    <inertial>
    <mass value="10.0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.1" ixy="0" ixz="0" 
            iyy="0.1" iyz="0" 
            izz="0.1"/>
    </inertial>

        <collision name='chassis_collision'>
        <origin xyz="0 0 ${chassis_size_z/2.0}" rpy=" 0 0 0"/>
            <geometry>
            <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
            </geometry>
        </collision>

        <visual name='chassis_visual'>
        <origin xyz="0 0 ${chassis_size_z/2.0}" rpy=" 0 0 0"/>
            <geometry>
            <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
            </geometry>
        <material name="Orange"/>
        </visual>
    </link>

<link name='chassis_head'>
    <pose xyz="0 0 0" rpy="0 0 0" />
    <inertial>
    <mass value="0.1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.1" ixy="0" ixz="0" 
            iyy="0.1" iyz="0" 
            izz="0.1"/>
    </inertial>

    <collision name='chassis_head_collision'>
    <origin xyz="0 0 ${chassis_size_z + chassis_size_z/8}" rpy=" 0 0 0"/>
        <geometry>
        <sphere radius="${chassis_size_x/4}"/>
        </geometry>
    </collision>

    <visual name='chassis_head_visual'>
    <origin xyz="0 0 ${chassis_size_z + chassis_size_z/8}" rpy=" 0 0 0"/>
        <geometry>
        <sphere radius="${chassis_size_x/4}"/>
        </geometry>
    </visual>
</link>
<joint name="chassis_head_joint" type="fixed">
<parent link="chassis"/>
<child link="chassis_head"/>
</joint>

<link name="back_wheel_chassis">
    <pose xyz="0 0 ${chassis_size_z}" rpy="0 0 0" />
    <inertial>
    <mass value="1.0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.1" ixy="0" ixz="0" 
            iyy="0.1" iyz="0" 
            izz="0.1"/>
    </inertial>

    <collision name='back_wheel_chassis_collision'>
    <origin xyz="${-(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0 ${-((chassis_size_z/2.0 - ground_gap_offset/2.0)/2.0)}" rpy=" 0 0 0"/>
        <geometry>
        <box size="${ground_gap_offset} ${ground_gap_offset} ${chassis_size_z/2.0 - ground_gap_offset/2}"/>
        </geometry>
    </collision>

    <visual name='back_wheel_chassis_visual'>
    <origin xyz="${-(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0  ${-((chassis_size_z/2.0 - ground_gap_offset/2.0)/2.0)}" rpy=" 0 0 0"/>
        <geometry>
        <box size="${ground_gap_offset} ${ground_gap_offset} ${chassis_size_z/2.0 - ground_gap_offset/2.0}"/>
        </geometry>
        <material name="brown"/>
    </visual>

</link>
<joint name="back_wheel_chassis_joint" type="fixed">
<parent link="chassis"/>
<child link="back_wheel_chassis"/>
</joint>

<link name="back_chassis_wheel">
    <pose xyz="0 0 0" rpy="0 0 0" />
    <inertial>
    <mass value="0.1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.1" ixy="0" ixz="0" 
            iyy="0.1" iyz="0" 
            izz="0.1"/>
    </inertial>
   
    <collision name='back_chassis_wheel_collision'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <sphere radius="${ground_gap_offset/2.0}"/>
        </geometry>
    </collision>

    <visual name='back_chassis_wheel_visual'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <sphere radius="${ground_gap_offset/2.0}"/>
        </geometry>
        <material name = "back_chassis_wheel">
            <color rgba="1 0 0 1"/>
            </material>
    </visual>
</link>

<joint name="back_chassis_caster_hinge" type="continuous">
<origin xyz="${-(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0  ${-((chassis_size_z/2.0- ground_gap_offset/2.0))}" rpy="0 0 0"/>
<parent link="chassis"/>
<child link="back_chassis_wheel"/>
<axis xyz="0 1 0" rpy="0 0 0"/>
<axis2 xyz="1 0 0" rpy="0 0 0"/>
</joint>


<link name="front_wheel_chassis">
    <pose xyz="0 0 ${chassis_size_z}" rpy="0 0 0" />
    <inertial>
    <mass value="1.0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.1" ixy="0" ixz="0" 
            iyy="0.1" iyz="0" 
            izz="0.1"/>
    </inertial>

          <collision name='front_wheel_chassis_collision'>
        <origin xyz="${(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0  ${-((chassis_size_z/2.0 - ground_gap_offset/2.0)/2.0)}" rpy=" 0 0 0"/>
            <geometry>
            <box size="${ground_gap_offset} ${ground_gap_offset} ${chassis_size_z/2.0 - ground_gap_offset/2.0}"/>
            </geometry>
        </collision>

        <visual name='front_wheel_chassis_visual'>
        <origin xyz="${(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0  ${-((chassis_size_z/2.0- ground_gap_offset/2.0)/2.0)}" rpy=" 0 0 0"/>
            <geometry>
            <box size="${ground_gap_offset} ${ground_gap_offset} ${chassis_size_z/2.0 - ground_gap_offset/2.0}"/>
            </geometry>
          <material name="Gray"/>
        </visual>

</link>
<joint name="front_wheel_chassis_joint" type="fixed">
<orgin xyz="${(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0  ${-((chassis_size_z/2.0- ground_gap_offset/2.0)/2.0)}" rpy="0 0 0"/>
<parent link="chassis"/>
<child link="front_wheel_chassis"/>
</joint>


<link name="front_chassis_wheel">
<pose xyz="0 0 0" rpy="0 0 0" />
     <inertial>
        <mass value="5.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.1" ixy="0" ixz="0" 
                iyy="0.1" iyz="0" 
                izz="0.1"/>
        </inertial>
   
    <collision name='front_chassis_wheel_collision'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <sphere radius="${ground_gap_offset/2.0}"/>
        </geometry>
    </collision>

    <visual name='front_chassis_wheel_visual'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <sphere radius="${ground_gap_offset/2.0}"/>
        </geometry>
        <material name = "front_chassis_wheel">
            <color rgba="1 0 0 1"/>
            </material>
    </visual>
</link>


<joint name="front_chassis_caster_hinge" type="continuous">
<origin xyz="${(chassis_size_x/2.0 - ground_gap_offset/2.0)} 0  ${-((chassis_size_z/2.0- ground_gap_offset/2.0))}" rpy="0 0 0"/>
<parent link="chassis"/>
<child link="front_chassis_wheel"/>
<axis xyz="0 1 0" rpy="0 0 0"/>
<axis2 xyz="1 0 0" rpy="0 0 0"/>
</joint>

<link name='left_wheel'>
<pose xyz="0 0 0" rpy="0 0 0" />
        <inertial>
        <mass value="5.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.1" ixy="0" ixz="0" 
                iyy="0.1" iyz="0" 
                izz="0.1"/>
        </inertial>

    <collision name='left_wheel_collision'>
        <origin xyz="0 ${wheel_length/2} 0" rpy="0 1.5707 1.5707"/>
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            </collision>

        <visual name='left_wheel_visual'>
        <origin xyz="0 ${wheel_length/2} 0" rpy=" 0 1.5707 1.5707"/>
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="left_wheel"/>
            </visual>
</link>

<joint name="left_wheel_hinge" type="continuous">
<origin xyz="0 ${chassis_size_y/2} 0" rpy="0 0 0"/>
<parent link="chassis"/>
<child link="left_wheel"/>
<axis xyz="0 1 0" rpy="0 0 0"/>
</joint>

<link name='right_wheel'>
<pose xyz="0 0 0" rpy="0 0 0" />
        <inertial>
        <mass value="5.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.1" ixy="0" ixz="0" 
                iyy="0.1" iyz="0" 
                izz="0.1"/>
        </inertial>

    <collision name='right_wheel_collision'>
        <origin xyz="0 ${-wheel_length/2} 0" rpy="0 1.5707 1.5707"/>
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>

        <visual name='right_wheel_visual'>
        <origin xyz="0 ${-wheel_length/2} 0" rpy=" 0 1.5707 1.5707"/>
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name = "right_wheel">
            <color rgba="1 0 0 1"/>
            </material>
        </visual>
</link>

<joint name="right_wheel_hinge" type="continuous">
<origin xyz="0 ${-chassis_size_y/2} 0" rpy="0 0 0"/>
<parent link="chassis"/>
<child link="right_wheel"/>
<axis xyz="0 1 0" rpy="0 0 0"/>
</joint>


<!---camera-->

<link name="camera">
 <box_inertia m="0.1" x="0.05" y="0.05" z="0.05">
 <origin xyz="0 0 0" rpy="0 0 0" />
</box_inertia>
    <inertial>
    <mass value="0.1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" 
            iyy="1e-6" iyz="0" 
            izz="1e-6"/>
    </inertial>
    <visual name='camera_visual'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="0.05 0.05 0.05"/>
        </geometry>
        <material name="camera"/>
    </visual>

    <collision name='camera_collision'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="0.05 0.05 0.05"/>
        </geometry>
    </collision>

</link>

<!--lidar-->
<link name="hokuyo">

    <inertial>
    <mass value="1e-5"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" 
            iyy="1e-6" iyz="0" 
            izz="1e-6"/>
    </inertial>

    <collision name='hokuyo_collision'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
        </geometry>
    </collision>

    <visual name='hokuyo_visual'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
       <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
        </geometry>
    </visual> 
     
</link>

<joint type="fixed" name="camera_joint">
<origin xyz="${chassis_size_y/2.0} 0 0" rpy="0 0 0"/>
<child link="camera"/>
<parent link="chassis"/>
<axis xyz="0 1 0" rpy="0 0 0"/>
<limit effort="10000" velocity="1000"/>
<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="camera_link_optical">
</link>

<joint name="camera_optical_joint" type="fixed">
<origin xyz="0 0 0" rpy="-1.5707 0 -1.5707"/>
<parent link="camera"/>
<child link="camera_link_optical"/>
</joint>



<joint type="fixed" name="hokuyo_joint">
<origin xyz="${(chassis_size_y/2.0)-0.05} 0 ${chassis_size_z+0.03}" rpy="0 0 0"/>
<child link="hokuyo"/>
<parent link="chassis"/>
<axis xyz="0 1 0" rpy="0 0 0"/>
<limit effort="10000" velocity="1000"/>
<dynamics damping="1.0" friction="1.0"/>
</joint>


<gazebo reference="camera">
    <material>Gazebo/Green</material>
  </gazebo>

   <gazebo reference="back_wheel_chassis">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="front_wheel_chassis">
      <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Orange</material>
  </gazebo>

   <gazebo reference="left_wheel">
    <material>Gazebo/Red</material>
  </gazebo>

   <gazebo reference="right_wheel">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="back_chassis_wheel">
    <material>Gazebo/Red</material>
  </gazebo>
   <gazebo reference="front_chassis_wheel">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="chassis">
    <material>Gazebo/Orange</material>
  </gazebo>

 


</robot>